### ISSUE TITLE
Noobproof readme?

### ISSUE THREAD

**Issue by megvadulthangya** [ich777/docker-iw4x-server#1]
Hi! Im fully noob in docker, i installed portrainer, then i pasted into the terminal this command: docker pull ich777/iw4x-server

What is next? :D Can you please create a readme for this? 
How to run it, and how can i configure after the container is running... etc Maybe you have a forum topic for this somewhere?
Thank you!

**Comment by ich777** [comment]
@megvadulthangya sorry that it took so long, updated the readme file, hope it's easy enough...

If you need any further assistance feel free to create a new issue. :)

**Comment by megvadulthangya** [comment]
Thank you Christoph! Works flawlessly on Debian 11 headless server.
Im still a noob, so i have a noob question... Can i modify somehow your
docker image to run plutoniumT4 server?
I think about copying and rename the copied one to something else...
O.o

Christoph ***@***.***> ezt írta (időpont: 2022. jan. 2., V,
19:03):
