### ISSUE TITLE
Can't Connect / Unable to find in Server Browser

### ISSUE THREAD

**Issue by DudeShift** [ich777/docker-iw4x-server#2]
Following the guide but using a VPS server:

- pulled docker image
- copied CoD:MW2 (iw4x full game install) to new directory
- ran the docker run example command but changing the volume to the new directory.
- Stopped the container
- edited the server name in ./players/server.cfg
- copied newest version of Bot Warfare mod 
- deleted container
- re-ran run command

When in game, trying to use /connect {my_VPS_IP}:28960 just says it timed out. Server is not on the browser list. 

When using a web browser and going to [{my_VPS_IP}:28960 does show a webpage for the server. ](https://i.imgur.com/u44evo3.png) I am unable to use the connect button since it tries to launch iw4x.exe and complains about not having a iw4x.dll (probably because its not launching through the xlab launcher)

I have tried using `sysctl -w net.ipv4.ip_forward=1` then `systemctl restart docker` to make sure the port was open.

Below is the output of container log ([also pastebin link](https://pastebin.com/p44PWtk2)):

---Ensuring UID: 99 matches user---
---Ensuring GID: 100 matches user---
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Taking ownership of data...---
---Starting...---
---Checking if IW4x is installed---
---Checking if IW4x DLC is installed---
---Checking if gamefiles are in place---
---Gamefiles found!---
---Checking if WINE workdirectory is present---
---WINE workdirectory found---
---Checking if WINE is properly installed---
---WINE properly set up---
---Prepare Server---
---Checking for 'server.cfg'---
---'server.cfg' found!---
---Checking for 'playlists.info'---
---'playlists.info' found!---
0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0050:err:systray:initialize_systray Could not create tray window
00f8:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 0926FEF8
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 59 (SPI_SETSTICKYKEYS)
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 51 (SPI_SETFILTERKEYS)
IW4x MP 0.7.5 build win-x86 Sep  4 2022

----- FS_Startup -----

Current language: english

'-dedicated +set net_port 28960 +exec server.cfg +sv_maxclients 12 +set fs_game 

mods/bots +set playlistFilename playlists.info'

Build 0.7.5 latest Sep  4 2022 10:14:15. Logfile opened on Tue Oct 18 20:49:10 2

Current search path:

Z:\iw4x\mods\bots\z_svr_bots.iwd (124 files)

Z:\iw4x/mods/bots

Z:\iw4x/userraw

Z:\iw4x\iw4x\iw4x_02.iwd (1 files)

Z:\iw4x\iw4x\iw4x_01.iwd (106 files)

Z:\iw4x\iw4x\iw4x_00.iwd (719 files)

Z:\iw4x/iw4x

Z:\iw4x\main\iw_dlc9_00.iwd (1387 files)

Z:\iw4x\main\iw_dlc8_00.iwd (2070 files)

Z:\iw4x\main\iw_dlc7_00.iwd (829 files)

Z:\iw4x\main\iw_dlc6_00.iwd (711 files)

Z:\iw4x\main\iw_dlc5_01.iwd (196 files)

Z:\iw4x\main\iw_dlc5_00.iwd (1986 files)

Z:\iw4x\main\iw_dlc4_01.iwd (274 files)

Z:\iw4x\main\iw_dlc4_00.iwd (1186 files)

Z:\iw4x\main\iw_dlc3_00.iwd (1350 files)

Z:\iw4x\main\iw_23.iwd (425 files)

Z:\iw4x\main\iw_22.iwd (430 files)

Z:\iw4x\main\iw_21.iwd (46 files)

Z:\iw4x\main\iw_20.iwd (86 files)

Z:\iw4x\main\iw_19.iwd (57 files)

Z:\iw4x\main\iw_18.iwd (61 files)

Z:\iw4x\main\iw_17.iwd (125 files)

Z:\iw4x\main\iw_16.iwd (171 files)

Z:\iw4x\main\iw_15.iwd (198 files)

Z:\iw4x\main\iw_14.iwd (406 files)

Z:\iw4x\main\iw_13.iwd (63 files)

Z:\iw4x\main\iw_12.iwd (31 files)

Z:\iw4x\main\iw_11.iwd (297 files)

Z:\iw4x\main\iw_10.iwd (556 files)

Z:\iw4x\main\iw_09.iwd (716 files)

Z:\iw4x\main\iw_08.iwd (886 files)

Z:\iw4x\main\iw_07.iwd (782 files)

Z:\iw4x\main\iw_06.iwd (481 files)

Z:\iw4x\main\iw_05.iwd (952 files)

Z:\iw4x\main\iw_04.iwd (1005 files)

Z:\iw4x\main\iw_03.iwd (1437 files)

Z:\iw4x\main\iw_02.iwd (1391 files)

Z:\iw4x\main\iw_01.iwd (1272 files)

Z:\iw4x\main\iw_00.iwd (1428 files)

Z:\iw4x/main

Z:\iw4x/main_shared

Z:\iw4x/players

Z:\iw4x/raw

Z:\iw4x/raw_shared

Z:\iw4x/devraw

Z:\iw4x/devraw_shared

Z:\iw4x\main\localized_english_iw07.iwd (860 files)

    localized assets iwd file for english

Z:\iw4x\main\localized_english_iw06.iwd (1474 files)

    localized assets iwd file for english

Z:\iw4x\main\localized_english_iw05.iwd (1635 files)

    localized assets iwd file for english

Z:\iw4x\main\localized_english_iw04.iwd (2164 files)

    localized assets iwd file for english

Z:\iw4x\main\localized_english_iw03.iwd (2741 files)

    localized assets iwd file for english

Z:\iw4x\main\localized_english_iw02.iwd (2732 files)

    localized assets iwd file for english

Z:\iw4x\main\localized_english_iw01.iwd (2524 files)

    localized assets iwd file for english

Z:\iw4x\main\localized_english_iw00.iwd (3013 files)

    localized assets iwd file for english

File Handles:

handle 1: logs/console_mp.log

----------------------

41384 files in iwd files

Adding channel: error

Adding channel: gamenotify

Adding channel: boldgame

Adding channel: subtitle

Adding channel: obituary

Adding channel: logfile_only

Adding channel: console_only

Adding channel: gfx

Adding channel: sound

Adding channel: files

Adding channel: devgui

Adding channel: profile

Adding channel: ui

Adding channel: client

Adding channel: server

Adding channel: system

Adding channel: playerweap

Adding channel: ai

Adding channel: anim

Adding channel: physics

Adding channel: fx

Adding channel: leaderboards

Adding channel: parserscript

Adding channel: script

Adding channel: network

No channels added or hidden

Adding channel: error

Adding channel: error

No channels added or hidden

Adding channel: gamenotify

Adding channel: obituary

No channels added or hidden

Adding channel: boldgame

No channels added or hidden

Adding channel: subtitle

No channels added or hidden

Loading fastfile code_pre_gfx_mp

Loading fastfile localized_code_pre_gfx_mp

Loading fastfile patch_code_pre_gfx_mp

execing default_mp.cfg from disk

execing default_mp_controls.cfg from disk

execing default_mp_controller.cfg from disk

No channels added or hidden

execing default_mp_gamesettings.cfg from disk

execing default_filter.cfg from disk

execing language.cfg from fastfile

========= autoconfigure

configure_mp.csv: using CPU configuration 8 GHz 1024 MB

execing configure_mp.cfg from fastfile

configure_mp.csv: using GPU configuration "*"

Parsing playlist 'playlists.info'...

CPU vendor is "GenuineIntel"

CPU name is "Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz"

3 logical CPUs reported

3 physical CPUs detected

Measured CPU speed is 2.90 GHz

Total CPU performance is estimated as 21.26 GHz

System memory is 2048 MB (capped at 2 GB)

Video card is ""

Streaming SIMD Extensions (SSE) supported

Winsock Initialized

Opening IP socket: localhost:28960

Hostname: e141992e80e3

IP: 172.17.0.3

UPNP: Testing device 'urn:schemas-upnp-org:device:InternetGatewayDevice:1' by se

nding packet to 239.255.255.250:1900

UPNP: Testing device 'urn:schemas-upnp-org:service:WANIPConnection:1' by sending

 packet to 239.255.255.250:1900

UPNP: Testing device 'urn:schemas-upnp-org:service:WANPPPConnection:1' by sendin

g packet to 239.255.255.250:1900

UPNP: Testing device 'upnp:rootdevice' by sending packet to 239.255.255.250:1900

----- Initializing Renderer ----

execing ragdoll.cfg from fastfile

----- Client Initialization -----

----- Client Initialization Complete -----

Loading fastfile code_post_gfx_mp

Loading fastfile localized_code_post_gfx_mp

Loading fastfile patch_mp

Loading fastfile iw4x_code_post_gfx_mp

0110:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0110:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
Loading fastfile localized_ui_mp

Loading fastfile ui_mp

Loading fastfile common_mp

Loading fastfile localized_common_mp

Loading fastfile iw4x_patch_mp

Loading fastfile iw4x_ui_mp

Loading fastfile iw4x_localized_english

GamerProfile - Updating for controller #0 without saving.

Reading profile for controller 0

GamerProfile - Updating for controller #0 without saving.

--- Common Initialization Complete ---

execing server.cfg from disk

g_gametype will be changed upon restarting.

Waited 144 msec for asset 'ui_mp/menus.txt' of type 'menufile'.

Huffman Took 1 Milliseconds

Error: Waited 8019 msec for missing asset "autoexec.cfg", of type "rawfile".

Error: couldn't exec autoexec.cfg

execing default_xboxlive.cfg from disk

xblive_rankedmatch is read only.

CL_Live_StartPrivateMatchHost() was called, calling Party_StopParty

Calling Party_StopParty() for partyId 0

Clearing migration data

Clearing migration data

Calling PartyHost_StartParty()

PartyHost_StartParty was called, calling Party_StopParty

Calling Party_StopParty() for partyId 0

Clearing migration data

Clearing migration data

execing default_xboxlive.cfg from disk

execing default_xboxlive.cfg from disk

We're going to be updating trueskill #0

Got our host key for our new party - xnkid (242.154.127.183...)

execing server.cfg from disk

g_gametype will be changed upon restarting.

Working directory: Z:\iw4x

Using profile source cloud (l:1 c:1)

No stats found, zeroing out stats buffer

execing mp/stats_init.cfg from fastfile

Calling XSessionSearchEx() looking for a lobby with 0 free slots, with playlist 

0, mapPack flags of 2, playlist version 0 - at time 10517

**Comment by ich777** [comment]
> When in game, trying to use /connect {my_VPS_IP}:28960 just says it timed out. Server is not on the browser list.

Have you opened the ports on your Firewall on your VPS, or is there any Firewall on your VPS? Both TCP & UDP  port `28960` should be forwarded.

I will try the container on my server ASAP and report back.

**Comment by ich777** [comment]
Server doesn't work anymore, I will deprecate this container since I can't maintain it anymore.

There is another container out there: https://hub.docker.com/r/dobolinux/iw4x-server
